/*Calculate total amount generated by all orders for high and low freight. */

SELECT
  SUM(CASE WHEN freight > 100 THEN amount ELSE 0.0 END) AS sum_high_freight,
  SUM(CASE WHEN freight <= 100 THEN amount ELSE 0.0 END) AS sum_low_freight
FROM orders;

| sum_high_freight | sum_low_freight |
| ---------------- | --------------- |
| 649633.80        | 616159.49       |