/*Show each category_id and category_name alongside the total_revenue generated by all order items from that category.*/

SELECT
	categories.category_id,
  	categories.category_name,
  	SUM(amount) As total_revenue
FROM categories
JOIN products
	ON categories.category_id = products.category_id
JOIN order_items
	ON products.product_id = order_items.product_id
GROUP BY categories.category_id, categories.category_name;


category_id | category_name  | total_revenue
------------|----------------|--------------
4           | Dairy Products | 234507.32
6           | Meat/Poultry   | 163022.38
2           | Condiments     | 106047.15
3           | Confections    | 167357.29
5           | Grains/Cereals | 95744.60
7           | Produce        | 99984.58
1           | Beverages      | 267868.20
8           | Seafood        | 131261.77